package Orchard.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = '64256b05-9d45-4726-ba53-4e9a64bf2e2e' (id = 'Orchard_Develop')
accordingly and delete the patch script.
*/
changeVcsRoot("64256b05-9d45-4726-ba53-4e9a64bf2e2e") {
    val expected = GitVcsRoot({
        uuid = "64256b05-9d45-4726-ba53-4e9a64bf2e2e"
        id = "Orchard_Develop"
        name = "Orchard_Develop"
        url = "git@github.com:aleksey-pyatlin/Orchard.git"
        branch = "dev"
        branchSpec = """
            +:refs/heads/*
            +:refs/pull/*/head
            +:refs/pull/(*/merge)
        """.trimIndent()
        authMethod = uploadedKey {
            uploadedKey = "Orchard_rsa"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "Orchard_rsa"
            passphrase = ""
        }
    }

}
