package Orchard.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = 'e59171e9-64f8-49e9-98c5-04d9c18d5008' (id = 'Supersite_CD_RND')
in the project with uuid = 'c58659de-f5ce-44b2-ab74-0aaa2149b179' and delete the patch script.
*/
create("c58659de-f5ce-44b2-ab74-0aaa2149b179", GitVcsRoot({
    uuid = "e59171e9-64f8-49e9-98c5-04d9c18d5008"
    id = "Supersite_CD_RND"
    name = "Supersite_CD_R&D"
    url = "https://git.itransition.com/scm/supersitev/supersitev5common.git"
    branch = "refs/heads/cd-rnd"
    authMethod = password {
        userName = "a.pyatlin"
        password = "zxxb4f01674e9f623a9b45f46eaac1bc2a0"
    }
}))

