package Orchard.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.ui.deleteVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the vcsRoot with uuid = 'e59171e9-64f8-49e9-98c5-04d9c18d5008' (id = 'Supersite_CD_RND')
from your code and delete the patch script.
*/
deleteVcsRoot("e59171e9-64f8-49e9-98c5-04d9c18d5008")

