package Orchard.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'c58659de-f5ce-44b2-ab74-0aaa2149b179' (id = 'Orchard')
accordingly and delete the patch script.
*/
changeProject("c58659de-f5ce-44b2-ab74-0aaa2149b179") {
    check(name == "Orchard") {
        "Unexpected name: '$name'"
    }
    name = "BAM"
}
