package Orchard.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '20e0f37b-07c3-4f24-ac32-ace119c349cd' (id = 'Orchard_Metrics')
accordingly and delete the patch script.
*/
changeBuildType("20e0f37b-07c3-4f24-ac32-ace119c349cd") {
    cleanup {
        add {
            all(builds = 5)
        }
    }
}
