package Orchard.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '8864e709-44b1-4f90-861c-c33eec236ae8' (id = 'Orchard_Publish')
in the project with uuid = 'c58659de-f5ce-44b2-ab74-0aaa2149b179' and delete the patch script.
*/
create("c58659de-f5ce-44b2-ab74-0aaa2149b179", BuildType({
    uuid = "8864e709-44b1-4f90-861c-c33eec236ae8"
    id = "Orchard_Publish"
    name = "Supersite_Publish"

    params {
        param("Configuration", "Debug")
    }

    vcs {
        root("Orchard_Develop")

    }

    triggers {
        vcs {
        }
    }

    features {
        commitStatusPublisher {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "zxx5237ed1d5ddd9778568f31b2e678d78c03a8eaede92d82f16ffebea53323c001d19456e0eed0717a775d03cbe80d301b"
                }
            }
            param("secure:github_password", "zxxa70075bc751d9d27eca19f64cb355703")
            param("github_username", "aleksey-pyatlin")
        }
    }
}))

