package Orchard.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.NUnitStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.VisualStudioStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.nunit
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.visualStudio
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'a1eff9e2-92dc-4432-9e54-2858b4aa7815' (id = 'Orchard_Develop')
accordingly and delete the patch script.
*/
changeBuildType("a1eff9e2-92dc-4432-9e54-2858b4aa7815") {
    expectSteps {
        script {
            name = "Restore packages"
            scriptContent = """call nuget restore src\Orchard.sln -Source "https://api.nuget.org/v3/index.json""""
        }
        visualStudio {
            name = "Build"
            path = "src/Orchard.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2015
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V14_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V14_0
            args = "/p:StaticAnalysisEnabled=true"
        }
        nunit {
            name = "Run Tests"
            nunitVersion = NUnitStep.NUnitVersion.NUnit_2_5_10
            runtimeVersion = NUnitStep.RuntimeVersion.v4_0
            includeTests = "/src/Orchard.Core.Tests/bin/%Configuration%/Orchard.Core.Tests.dll"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = """
                echo "test"
                
                call nuget restore src\Orchard.sln -Source "https://api.nuget.org/v3/index.json"
            """.trimIndent()
        }
    }
}
